
workflows:
  ios_shake_flashlight_build:
    name: Shake Flashlight iOS App Build
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          cd ShakeFlashlight
          pod install
      - name: Build the Xcode archive
        script: |
          xcodebuild -workspace ShakeFlashlight.xcworkspace \
            -scheme ShakeFlashlight \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ShakeFlashlight.xcarchive
      - name: Export IPA file
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ShakeFlashlight.xcarchive \
            -exportOptionsPlist $CM_SOURCE_DIR/exportOptions.plist \
            -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
